const SubmissionStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAYMENT_REVIEW: 'PAYMENT_REVIEW',
  MARKING_ESSAY: 'MARKING_ESSAY',
  ESSAY_MARKED: 'ESSAY_MARKED',
  QUESTION_ASKED: 'QUESTION_ASKED',
  SUBMISSION_COMPLETED: 'SUBMISSION_COMPLETED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_FAILED: 'REFUND_FAILED',
  SUBMISSION_CANCELED: 'SUBMISSION_CANCELED'
};

export default SubmissionStatus;